[package]
name = "winfetch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.chrono]
version = "0.4.19"

[dependencies.winapi]
version = "0.3.9"
features = [
    # shared
    "minwindef",
    "ntdef",
    "rpcdce",
    "windef",
    "winerror",
    "wtypesbase",
    "wtypes",

    # um
    "combaseapi",
    "oaidl",
    "objbase",
    "objidl",
    "oleauto",
    "sysinfoapi",
    "tlhelp32",
    "wbemcli",
    "wingdi",
    "winnt",
    "winreg",
    "winuser"
]
